#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider;
use Illuminate\Html\HtmlServiceProvider;
use Orchestra\Testbench\Traits\ApplicationTrait;
use Orchestra\Testbench\Traits\ClientTrait;
use Radic\BladeExtensions\BladeExtensionsServiceProvider;

class Artisan
{
    use ApplicationTrait, ClientTrait;



    /**
     * @var Artisan
     */
    protected static $factory;
    /**
     * @return \Illuminate\Foundation\Application
     */
    public static function start()
    {
        static::$factory = new Artisan();
        return static::$factory->createApplication();
    }

    /**
     * Define environment setup.
     *
     * @param  \Illuminate\Foundation\Application $app
     * @return void
     */
    protected function getEnvironmentSetUp($app)
    {
        // Define your environment setup.
    }
}

$app = Artisan::start();
$app->register(new IdeHelperServiceProvider($app));
$app->register(new HtmlServiceProvider($app));
$app->register(new BladeExtensionsServiceProvider($app));
//$config = $app->config->get('blade-extensions');


$kernel = $app->make('Illuminate\Contracts\Console\Kernel');
$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);
