#!/bin/bash

pdir=$PWD


function _grip {
    local file=$1
    local noext=`echo $1 | sed 's/.md//g'`
    local lcase="${noext,,}"

    grip $1 --gfm --context=robinradic/blade-extensions --export $2.html
}

function makedoc {
    rm -rf docs/html/* >> /dev/null


    echo "Generating documentation"
    mkdir -p $pdir/docs/html/docs
    cd docs
    _grip $pdir/docs/.index.md $pdir/docs/html/index
    for file in *.md; do
        destfile=`echo $file | sed 's/.md//g'`
        _grip $pdir/docs/$file $pdir/docs/html/docs/$destfile
    done
    cd $pdir

    echo "Generating API documentation"
    php vendor/bin/pinocchio --source src --output docs/html/api

    chromium $pdir/docs/html/index.html
}

function servedoc {
    echo "Creating static server hosting .md docs"
    grip --gfm --context=robinradic/blade-extensions
}

function test {
    echo "Starting tests"
    php vendor/bin/phpunit -c phpunit.xml
}

function testc {
    echo "Starting tests and generating coverage"
    rm -rf docs/html/api/* >> /dev/null
    php vendor/bin/phpunit -c phpunit.xml --coverage-html docs/html/coverage
}

function test2 {
    echo "Starting tests"
}

function test3 {
    echo "Starting tests"
}

function test4 {
    echo "Starting tests"
}

function dist {
    testc
    makedoc
}


$*
