#!/usr/bin/env bash

echo "pre commit hook start"

CURRENT_DIRECTORY=`pwd`
GIT_HOOKS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

PROJECT_DIRECTORY="$GIT_HOOKS_DIR/../.."

cd $PROJECT_DIRECTORY;
PHING="vendor/bin/phing"
HAS_PHING=false
if [ -x "$PHING" ]; then
    HAS_PHING=true
fi
if $HAS_PHING; then
    echo "Have phing"
else
    composer install
fi

$PHING -f build.xml pre-commit

cd $CURRENT_DIRECTORY;
echo "pre commit hook finish"
