#!/usr/bin/env bash

echo "pre commit hook start"

CURRENT_DIRECTORY=`pwd`
GIT_HOOKS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

PROJECT_DIRECTORY="$GIT_HOOKS_DIR/../.."

cd $PROJECT_DIRECTORY;
PHING="$PROJECT_DIRECTORY/build/bin/phing"
HAS_PHING=true
if [ -x "$PROJECT_DIRECTORY/build/bin/phing" ]; then
    PHING="$PROJECT_DIRECTORY/build/bin/phing"
elif [ -x "$PROJECT_DIRECTORY/vendor/bin/phing" ]; then
    PHING="$PROJECT_DIRECTORY/vendor/bin/phing"
elif [ -x "$(which phing)" ]; then
    PHING="$(which phing)"
else
    HAS_PHING=false
fi

if $HAS_PHING; then
    $PHING -f build.xml pre-commit
else
    echo "Phing not found"
fi


cd $CURRENT_DIRECTORY;
echo "pre commit hook finish"
